### ISSUE TITLE
Adding package fails on Alpine 3.8

### ISSUE THREAD

**Issue by joeschmid** [sgerrand/alpine-pkg-php5-imagick#2]
Thanks for providing this! It's been working great for us on Alpine 3.7.

With Alpine 3.8 when doing:

`apk --no-cache add ca-certificates wget
 wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-php5-imagick/master/sgerrand.rsa.pub
 wget https://github.com/sgerrand/alpine-pkg-php5-imagick/releases/download/3.4.3-r0/php5-imagick-3.4.3-r0.apk
 apk add php5-imagick-3.4.3-r0.apk`

We get the following error:

`ERROR: unsatisfiable constraints:
  php5-imagick-3.4.3-r0:
    masked in: cache
    satisfies:
               world[php5-imagick><Q1xePUeXBtkYJjBThe3c0TjjUtkwE=]
  so:libMagickCore-7.Q16HDRI.so.4 (missing):
    required by:
                 php5-imagick-3.4.3-r0[so:libMagickCore-7.Q16HDRI.so.4]
  so:libMagickWand-7.Q16HDRI.so.4 (missing):
    required by:
                 php5-imagick-3.4.3-r0[so:libMagickWand-7.Q16HDRI.so.4]`

(The imagemagick package is installed.)

If we can provide more info, don't hesitate to let me know. We'd love to help make this work for Alpine 3.8

**Comment by Daynnnnn** [comment]
I came across this issue today and opted just to build imagick from source, hopefully this helps somebody:

```
# Imagick
RUN apk add --no-cache autoconf php5-dev gcc make g++ zlib-dev wget imagemagick-dev && \
    mkdir /imagick && cd /imagick && \
    wget http://pecl.php.net/get/imagick-3.4.4.tgz && \
    tar xzf imagick-3.4.4.tgz && cd imagick-3.4.4 && \
    phpize5 && ./configure --prefix=/usr --with-php-config=php-config5 && \
    make && \
    cp modules/imagick.so /usr/lib/php5/modules/ && echo "extension=imagick.so" > /etc/php5/conf.d/imagick.ini && \
    apk del autoconf php5-dev gcc make g++ zlib-dev
```

Tested on 3.8, not the nicest solution but works for me.

**Comment by sgerrand** [comment]
Apologies all for the delay on addressing this issue. I'm working on it now.
